url = "https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz"
supportsRosetta = false

[dependencies]
dependencies = []
buildDependencies = []
optionalDependencies = []


[intel]
hash = "30af1df2395bb81457c3bd59ed3c3cd272f115a0e70aeca527509779455b6c1c"

[silicon]
hash = "3c67ca9fee757ee29e67396286ce840142bfa331cfc5e194514fea08d8134007"
